### ISSUE TITLE
Additional Compression Library

### ISSUE THREAD

**Issue by xorhex** [binref/refinery#20]
Can lzf be added to the decompression functionality as well?

Basically this project: https://github.com/teepark/python-lzf

**Comment by huettenhain** [comment]
I would prefer to reimplement this as pure Python to avoid depending on a wrapper library for C code, I consider those fairly unstable. However, the decompression for this LZ variant looks straightforward enough, I am sure I can re-implement this. I'll get on it.

**Comment by huettenhain** [comment]
As expected, this is fairly straightforward. I'll see if the tests pass for e4a05cc1b6ed71a1f5eea69ae495fc77d3f0bdf6, next I will check that adding `lzf` to the suite for the `decompress` unit also works without breaking anything.

**Comment by huettenhain** [comment]
I had to twist and refactor the universal decompressor a bit in ecca3f2ff6a6b916894b8fe522129e7077bc5c51, but once the checks for that commit are through, I can push out a new release with LZF support.

**Comment by huettenhain** [comment]
The `lzf` unit and LFZ support for the `decompress` unit are now present in release 0.4.44. Cheers!

**Comment by xorhex** [comment]
Wow, that was fast!  Thank you @huettenhain!
