### ISSUE TITLE
Fish support

### ISSUE THREAD

**Issue by lennihein** [binref/refinery#22]
`emit` is already a [command in fish](https://fishshell.com/docs/current/cmds/emit.html). 

```fish
alias emit (which emit)
```
seems to be a suitable workaround

**Comment by larsborn** [comment]
Would using a "prefix" be a solution for you (see [the ](https://github.com/binref/refinery/blob/master/README.md)).

**Comment by lennihein** [comment]
@larsborn 

> Would using a "prefix" be a solution for you (see [the ](https://github.com/binref/refinery/blob/master/README.md)).

I suppose that would be a solution. On my system it kept installing binref _without_ the prefix since the packages were still cached! Removing the `.cache/pip/` folder fixed it. 

I'll keep updating this thread while I continue using binref with Fish.

**Comment by huettenhain** [comment]
If you can think of a more satisfying solution than having to use a prefix, we should definitely re-open this and try to implement it. I will also install fish and try out a few things to get a better feel for the shell.

**Comment by jhhcs** [comment]
The current behavior in both a virtual environment and everywhere else is that fish's internal `emit` command wins out over any executables that exist on the path, which is what I expected, unless you explicitly use an alias like @lennihein suggested. 

One option that obviously comes to mind is to rename the `emit` unit to something else. The main effort on my part is that I would have to change a lot of existing documentation, and the main problem is that there is documentation that I _cannot_ edit, like the OALabs video and Johannes Bader's blog post.

My current suggestion would be to do the following:
```
alias event-emit="builtin emit"
alias emit=(which emit)
```
This preserves the ability to use fish's builtin `emit` by running `event-emit` while `emit` will be the corresponding refinery unit.

**Comment by jhhcs** [comment]
PS: Lots of interesting stuff on how to work with aliases in [this stackexchange post|https://unix.stackexchange.com/q/39291].
