### ISSUE TITLE
iemap does not display colour

### ISSUE THREAD

**Issue by cxiao** [binref/refinery#27]
### Description
I have noticed that in my environment, the `iemap` unit does not produce any colour, which unfortunately makes the unit not very useful. Other units which produce colour, such as `peek`, do emit colour in their output as expected.

### To Reproduce
This behaviour is reproducible on both Linux and MacOS. Just for reproducing this bug, I created a new Python virtual environment on both the Linux and MacOS machines, and did a fresh install of Binary Refinery inside it, via `pip install binary-refinery[all]`. 

I have included screenshots below of the output of the `peek` unit, as well as the `iemap` unit. I passed the `--legend` flag to `iemap` in this case, and expect to see colours in at least the numbered legend to the left of the entropy graph.

- Operating System: Fedora Linux 37
- Python Version: 3.11.2
- Refinery Version: 0.6.0
- Shell: Bash
- Terminal Emulator: gnome-terminal

![image](https://user-images.githubusercontent.com/1661230/230247814-49b3c591-3dda-4091-b69b-89ef1a761708.png)

- Operating System: MacOS Ventura
- Python Version: 3.10.1
- Refinery version: 0.6.0
- Shell: Zsh
- Terminal Emulator: iTerm2

![image](https://user-images.githubusercontent.com/1661230/230254408-02dc1d2a-6c05-4a71-85d5-2079115a5273.png)

**Comment by jhhcs** [comment]
Yep, I can reproduce this. Working on a fix.

**Comment by huettenhain** [comment]
I think this should fix it. Once the deployment is through, would you mind updating to 0.6.1 and verify that it's working now? I am not at all sure my test is testing what I think it is testing. Hard to test for color.
