### ISSUE TITLE
rc5 and rc6: CTR mode does not work

### ISSUE THREAD

**Issue by nmantani** [binref/refinery#29]
### Description
rc5 and rc6 cannot encrypt with CTR mode since version 0.5.10.

### To Reproduce
Master:
```bash
$ echo -n  "This is a secret message." | rc5 -m ctr -i 01234567 -R 0123456789abcdef
(00:44:40) failure in rc5: exception of type ValueError; Information in counter object does not align with block size.
$ echo -n  "This is a secret message." | rc6 -m ctr -i 0123456789abcdef -R 0123456789abcdef
(00:45:03) failure in rc6: exception of type ValueError; Information in counter object does not align with block size.
$
```
Version 0.5.9 works:
```bash
$ echo -n  "This is a secret message." | rc5 -m ctr -i 01234567 -R 0123456789abcdef | rc5 -m ctr -i 01234567 0123456789abcdef
This is a secret message.
$ echo -n  "This is a secret message." | rc6 -m ctr -i 0123456789abcdef -R 0123456789abcdef | rc6 -m ctr -i 0123456789abcdef 01
23456789abcdef
This is a secret message.
$
```

### Environment
- Operating System: Ubuntu 20.04.6 LTS (WSL2)
- Python Version: 3.8.10
- Refinery Version: master

**Comment by huettenhain** [comment]
Looking into this now. I probably broke something when I fixed other stuff. You can just never have enough tests.

**Comment by huettenhain** [comment]
As suspected, this was an artefact of previous fixes that had slipped through the test coverage. We have a regression test for this now and a fix. Once the tests are through and everything is looking green, I will release a bugfix version.

**Comment by nmantani** [comment]
Thank you very much for fixing it!

**Comment by huettenhain** [comment]
I am also releasing 0.6.2 as a bugfix release right now, so this should soon be fixed in the latest pypi version as well. Cheers and thanks for the bugreport!
