### ISSUE TITLE
machometa

### ISSUE THREAD

**Issue by g-les** [binref/refinery#35]
### Specification
Unit Request for machometa 

Requesting a new unit to perform similar functionality as pemeta, but for macho executables. The data requested inside of this would ideally include:
 - Header info (machine arch, num of load commands, etc  -  this is already parsed in peek)
 
 - Dylibs (externally linked dependencies / libs - lief can parse this )
 
 - Code-signing information (mostly just the name but if extracting other information is readily do-able, that would be great! Example parsing in Go: https://github.com/blacktop/go-macho/blob/master/pkg/codesign/codesign.go ) 
 
 - Imports/Exports/Symbols (optional flag - lief can parse this information)
 
 - Class Information (Not necessary but cool as an option flag - ObjC files only) (via class-dump - not python :( https://github.com/nygard/class-dump ))

I realize I'm not giving a ton of great info here but I'm currently using a bunch of Apple utilities or python snippets to triage Macho samples and I figured others would benefit from this being in binref :) 

### Example (awful) Parsing Code to show dylibs and signature data - works for most ARM and x86 bins but not FATs 
```
import sys
import lief
from hashlib import md5
import argparse
import os

def main():

	parser = argparse.ArgumentParser(description="Macho Sig Name Extraction")
	parser.add_argument("-f", "--file", help="Specify file to parse", metavar="<file>", required=False)
	args = parser.parse_args()

	result = sig_reading(args.file)
	if result is not None:
		print("\tTarget File: \t" + result[0])
		print("\tFile MD5: \t" + result[1])
		print("\tSig Name: \t" + result[2])
		print("\tDylibs: \t")
		for i in result[3]:
			print("\t\t"+i)



def sig_reading(target):

	dylibs = []

	try:
		target_macho = open(target, mode="rb")
		contents = target_macho.read()
		file_hash = md5(contents).hexdigest()
		parsed_macho = lief.parse(target)
		for lib in parsed_macho.libraries:
			dylibs.append(lib.name.lower())
		cs_sign_dir_offset = parsed_macho.code_signature.data_offset

		# read the big CS directory & get ptr to 0th blob
		target_macho.seek(cs_sign_dir_offset)
		cs_dir_bytes = target_macho.read(0x20)
		jump_to_blob = cs_dir_bytes[19]

		# read the 0th blob and look for ident ofset
		target_macho.seek(cs_sign_dir_offset+jump_to_blob)
		first_codesign_blob = target_macho.read(0x20)
		jump_to_ident = first_codesign_blob[23]

		# read identifier string
		target_macho.seek(cs_sign_dir_offset+jump_to_blob+jump_to_ident)
		ident_str = target_macho.read(0x30)
		sig_name = str(ident_str)
		sig_name = sig_name.split('\\x00')[0]
		sig_name = sig_name[2:]
		target_macho.close()
	except:
		print("not a macho")
		return


	sig_list = [target,file_hash,sig_name,dylibs]
	return sig_list
main()
```

**Comment by huettenhain** [comment]
Do you happen to have a signed MachO-Binary that I can work with?

**Comment by huettenhain** [comment]
One note straight off the bat: I tried LIEF before (there's even [a branch called lief](https://github.com/binref/refinery/tree/lief)), but it had too many issues to make it into the main branch. Tragically enough, one main reason to discard it was that it failed to parse a sample Mach-O file. Furthermore, LIEF has some performance issues; for example, it is outperformed by the pure-python pefile module for signature extraction, see https://github.com/lief-project/LIEF/issues/832#issuecomment-1342320348.

I am currently still using the [macholib](https://github.com/ronaldoussoren/macholib) library to parse Mach-O files. I am reluctant to include LIEF _only_ for the machometa unit; my dependency tree is already way too bloated and I would prefer to prune it rather than extend it. If it is at all possible, I would much prefer to do this with macholib, but I am not yet sure if that's feasible.

**Comment by g-les** [comment]
Ad-hoc signed Macho: https://bazaar.abuse.ch/sample/6c121f2b2efa6592c2c22b29218157ec9e63f385e7a1d7425857d603ddef8c59/

Apple Authorized Signed Macho: https://bazaar.abuse.ch/sample/a64fa9f1c76457ecc58402142a8728ce34ccba378c17318b3340083eeb7acc67/

in regards to using macholib - I'll check it out! totally understand not wanting to bring lief in if its caused issues before. I'll investigate using it!

**Comment by g-les** [comment]
initial look makes me thing it can't grab the signature data in a straightforward manner (https://github.com/ronaldoussoren/macholib/blob/0f77e700f84690121bba872470bc825cecd23d97/macholib/MachO.py#L326), but it will grab the LoadCommand for it, so theoretically we could manually parse it from there. 

it looks like dylibs can be extracted via  macholib.dylib.dylib_info in some form. 

for https://bazaar.abuse.ch/sample/6c121f2b2efa6592c2c22b29218157ec9e63f385e7a1d7425857d603ddef8c59/, the dylibs & signature identifier are: 

```
	Dylibs: 	
		/system/library/frameworks/foundation.framework/versions/c/foundation
		/usr/lib/libobjc.a.dylib
		/usr/lib/libc++.1.dylib
		/usr/lib/libsystem.b.dylib
		/system/library/frameworks/corefoundation.framework/versions/a/corefoundation


	Sig Name: 	payload2
```

**Comment by huettenhain** [comment]
Sweet. I am sure I can figure this out. Full disclosure, though: We have a 3 weeks old newborn right now and I'll need a bit longer to get this done than usual xD.

**Comment by g-les** [comment]
@huettenhain go have fun with the kid - those early days are precious, and thats much more important than my silly unit request <3

**Comment by g-les** [comment]
Might be a nice alternative to lief! 

https://github.com/cxnder/ktool

**Comment by huettenhain** [comment]
This looks terrific! As I've already said through other channels: I would be extremely happy about a PR. Replacing the old and somewhat stale `macholib` with `ktool` would be my next goal, but we don't have to do that as part of this PR (and I don't think we should, either).

**Comment by g-les** [comment]
this is tremendous @cxiao thank you!! 

all of this is very helpful to me - I appreciate you taking the time to build this out. I think it it will make triage of Macho files MUCH easier for the whole community so we don't have to use 6 or 7 different CLI tools to get this information :)

**Comment by huettenhain** [comment]
PR it already @cxiao

**Comment by huettenhain** [comment]
@cxiao BUMP

**Comment by g-les** [comment]
great news @cxiao !! I'll be shouting this from the rooftops!

**Comment by huettenhain** [comment]
I came here to close the issue out, but you were way ahead of me it seems. Good hustle, cyber fam. Thanks again to @cxiao for implementing this. Best PR I've ever seen, hands down.
