### ISSUE TITLE
Feature Request: Add Support for Converting from Base92

### ISSUE THREAD

**Issue by mosheDO** [binref/refinery#48]
Consider adding support for converting from base92.

This addition would broaden its functionality and cater to users who may encounter data encoded in this format.

Regards, Moshe

**Comment by huettenhain** [comment]
What a crude and poorly documented encoding format. I added support in c2435fd4595826c7401559b68403bf1c7a7be3f1 and then wrestled the test suite for a bit. I will release a new version soon that includes the `b92` unit for Base92 encoding and decoding.

**Comment by mosheDO** [comment]
Thanks for the effort, I looked on your commit (I'm not familiar with the project)
But I think you have a typo mistake in your code

[__init__.py](https://github.com/binref/refinery/blob/1ee16603bbdbaa6432797576f252b3984e950446/refinery/lib/patterns/__init__.py#L33)


It supposed to be `"Base92 encoded strings"` instead of `"Base64 encoded strings"`

**Comment by huettenhain** [comment]
Ha, indeed, thanks. Fixed in a30cdea20d6d500ac0956482de2fc073fff602d1. Regardless, Base92 is now supported in version 0.6.39, so I will close out this issue. Cheers!
