### ISSUE TITLE
Full Install fails under Python 3.7 due to PyPCAPKit dependency

### ISSUE THREAD

**Issue by jhhcs** [binref/refinery#51]
Installing `binary-refinery[all]` currently fails because of [this issue with PyPCAPKit](https://github.com/JarryShaw/PyPCAPKit/issues/221).

**Comment by jhhcs** [comment]
I will wait 72 hours for the PyPCAPKit / dictdumper problem to be resolved; if there is no progress within that time, I'll implement a temporary fix. By freezing `dictdumper==0.8.4`, for example, installing `pypcapkit[scapy]<0.16.0` will continue to work as expected.

**Comment by jhhcs** [comment]
Once this is fixed, we should also revert https://github.com/binref/refinery/commit/3966e53c69bcf8907d5e9dc503099808dc53e462 which implements the `dictdumper` trick for the test suite only.

**Comment by huettenhain** [comment]
As announce, I have pushed a workaround in 30d24be and I am releasing [0.6.42](https://github.com/binref/refinery/tree/0.6.42) as a (temporary) bugfix release. Keeping this ticket open until the root cause is resolved.

**Comment by huettenhain** [comment]
Since this has been stale for a while, I decided to switch the refinery requirement to Python 3.8, which magically makes this problem go away.
