### ISSUE TITLE
IFPS Parsing issue with external dll function return type

### ISSUE THREAD

**Issue by gdesmar** [binref/refinery#56]
### Description
When reading this specific IFPS file with the IFPS unit, the following error happens:
> failure in ifps: exception of type EOFError

### To Reproduce

The original [InnoSetup file](https://bazaar.abuse.ch/sample/258ecd1cb153a2a450ad5404f7c55a7dea44edb54da650ffa1165d7158dee94b) gives out an IFPS file named [CompiledCode.bin](https://github.com/user-attachments/files/16753237/fb0fc2e3c2059e6159540920a4ff7f75f92212639b318da7eb7fadece4a46ecc.zip) (attached, with password `binref`). If we `emit` that file into `ifps` or `ifpsstr`, we get the previous error.

### Environment
- Operating System: Debian bullseye
- Python Version: Python 3.11.7
- Refinery Version: Tested with both binary-refinery==0.6.43 and the current [master branch](https://github.com/binref/refinery/commit/ef049a4aa06ac56568e92546e5c9ae5d633d91aa)

### Additional Context
The error comes from the sixth function (kernel32.dll::GetTickCount) which is [imported](https://github.com/binref/refinery/blob/0.6.43/refinery/units/formats/ifps.py#L690) and is a dll, but doesn't seem to have enough data to read the [return type](https://github.com/binref/refinery/blob/0.6.43/refinery/units/formats/ifps.py#L405).

I see that the IFPS unit is based on IFPSTools, which was superseeded by [IFPSTools.NET](https://github.com/Wack0/IFPSTools.NET). I ran IFPSTools.NET on the same file and it gave a decoded file back claiming that function is void=True.

To get the CompiledCode.bin out of the InnoSetup file, we can use [innounp](https://github.com/WhatTheBlock/innounp) on Windows/Wine with the password `A1ADB8BE8E677894E`, or a custom version of [innoextract](https://github.com/gdesmar/innoextract/releases) (which doesn't need the password) on Linux.

**Comment by huettenhain** [comment]
Just confirming that this is on my radar; planning to look into it more closely this weekend.

**Comment by huettenhain** [comment]
Alright it was less difficult than I thought. The [relevant code in IFPSTools.NET](https://github.com/Wack0/IFPSTools.NET/blob/master/IFPSLib/Emit/ExternalFunction.cs#L133) performs a version check that my code doesn't include before parsing two fields in the function signature. I already have the fix implemented, I just want to add your sample as a test.

**Comment by huettenhain** [comment]
I also released a new version, it's [currently being published](https://github.com/binref/refinery/actions/runs/10586662027).
