### ISSUE TITLE
Jump & Conditional Jumps

### ISSUE THREAD

**Issue by Ben4FH** [binref/refinery#57]
I have combed through the documentation but can't seem to find this feature. I would like to be able to perform loops through data similar to the Jump and Conditional Jump instructions in CyberChef. I've provided a simple example below but obviously it could be made more complicated.

[Jump - Reverse string & b64 decode 21 times](https://gchq.github.io/CyberChef/#recipe=Label('top')Reverse('Character')From_Base64('A-Za-z0-9%2B/%3D',true,false)Jump('top',20)&input=UVJWTUNabFZhRldUR3BFV09WRlpvTkZNYWhGVlhaMGJOWmxXNGRsYUNaVllIaG1SWlJsUWhKVmJLcG5XSGgzVmxkVU95bFZNT1JqVXhBM1ZPVmxWcGRWYlNWblZ3UTJVU0JUTVlGRmJTQmxUVlZ6Vlo1R2FPWkZiYVZ6VVVaMFZXcG5WMFpWVm90VVRXcEVTUFJsU1hOV013ZGtWd1V6U1Nka1YySTJSNGRWWXpJRmRXNW1UTFpGYmtoMVlIRmpVanhHY0haMWFrOVdZeFFHU1ZwbVNWVkZNS1ZGVlZGelNpWmxTb3BsUmFGbVVWQm5jV3htVmhKbVJTMWtVclJXYVZCalcwWkZNV0ZtVVhaVVlWMUdlWFpWTXdkRlZYWjBhaXhtVzZWMWFraEZWeG8xUlgxV09YSjJWR1IwVnNaRldqRlRTNVZWVjFjVVlzUjJNV1JsUm9KbU1vZDFWV3AxVldaa1dYVlZiNFoxVkY5V2VWdEdadjFrUmFCalZ0QkhXVkJEY0ZwRld3TmxZR3BsY2FkVU5hWjFNQ1psV1dkR2VTSmpWNk5GYmE1MFV5ZzNjVzVtVmgxMFZTOTBWdFJYVlZka1VYbGxhUzlXVFdwRldScG1UVGRsYUdSWFZ1bEVlaEZqVzZOR1JPcGxVczlHZVpaRlpMRkdiV2gwWUdwMVVpSmpVeVpGV3NablZYNTBiVjFHZFZkbFJKbFhWdGx6Y1d4R1pZVmxhS0psVnhvbFZVcG1SMlpGYktoV1lGcDFWa0pUT0hwbFJrRldUV0JITk5kRWRUVmxNbmxuVnVKMVVUWkVaV0oxYVNwMlZHcDBWVzVHWlAxVU1XaDBZRVowVmh4bVN5VkZXQ3RtWUdwME1UMVdOWDUwYXZoblZIeDJhaEZqU0dKVmJ4TVZZeUkxVlg1bVVUSlZNT2gyVnJaVllUVjBiNFYxYWtOWFRXWmxlalprV29aVlJhRlhWeGcyYU5kbFIycGxSV0YyWXpJMFZaRkRhd0ltVmtoSFZ0aDNVWmRsVUhaRmJzOWtWd1VEY1h0bVdwTlZWMWdVVnI1MGNpWmxXS0ZXUmt0bVZ3VVRjVlpsUUwxMFZHTmpXeVV6VlhkMFo2WkZib05sVnNsbGVXdG1XTzFVVldSM1ZWUjJVU0JUTllOMlJ4UWxWR3BGZFZ0bVd2SkdiYWhWVnFwa1VVdG1XeFZsTW5GalZXcGxjU3BtU1dKMWFLbGtXR1JHTlNGRGNGSjFha2xXVnlFRmVXNW1TMzFrVmFsVlRYRmpWbHhHY1haVmIwdDJWR0pGV2laa1dPWmxWd05uVnhvVllOZGxSb1pWYjBkMVl3bzFSYVpGWkRaVlIxRTJZR3AxVVpkRmF6ZEZXb1puVlhKRldSdG1Vb1JtYUdaVVdyaFROV0ZEY0pKVmJ3ZDFWc0IzY1ZORGN6WkZiWmQzVFhSM1ZqQlRTNlZGYktCallXWmxlWHBtUk9WVk1LVm5WdWhtU1d4R2JQZFZiNFIxVlhKMVZacG1VckpGYndsVVlHUkdXV3BuUklsbGVDcGtZRkZEVWlkRWRhSjFNQ2RWV1ZWelVTZFZTM3BsUmFkVll3b0ZkVzVtVWhaVmJPaFZUVlIyYVhWVk4wVmxiYTkyVkdSMlZWcG1UWFpWTXdkMFZxSmtTaWRsVklwbFJhcDFWRkIzY1pGalcwSW1WWnBYVFhSM1ZUMUdhWlpsZWFGV1l4UTJja1ZFWnBWbVZhZFVXdVJHTWlaRmJJTkdSQ2xXVnpnR1NYdFdPSDEwYXhNVVlIVnpWa1YxYjRsRmJvdFdZeG9VVlV4bVdwUldNd2QxVnNSMlFOSmpUaDFVVmtCVlpHeDJWVVpsVERWR2JzZDBWcVowVldoRmFJbEZNb3RtVXRwMFVTeG1VVkoxTUJoblZYaFdZU2RsUmFwMVI0TkZadEpWV1dORGFTMUViS1IxVnJabGFoVjBiNGwxVjA5VVRXWjFNVlZsVXNaMU1TaFVXcmgzU1MxbVNRSlZieGMxWXVKMFJaWmxWWEoxVk5kblZxWkVhTmhrVXlkRldPRm1VdFpGVVYxR2VTZFZSYVJIVlc1VVlXWkZaWEZGYm9wVlZ6SUZTVVJsVUwxa1ZhUnpWVVowVlNaRmN6WkZia3RrVUhwVVZTeEdaT05WTXdWblZZcDBVaVpsVVZGRmJTaGxUc0IzUloxR2RQWkZiU0J6VXJwMVZpWmtXR2RWYm90bVlHcEVUaFprV1hSbVJKcFhWczUwUmh4MlkzSlZWYWRGVnpFVWVXNW1WdkpsTVNoVllIUkhXaFZFYzBWVmJHdGtZc1JXU2hkVU5ZWmxSYWRWVjZwVllOWmxXMkpWYnhZRlpFWmxjVXhHYTNKbVZLQlZWc1JtVGtGVFc2WkZiYU5WVHRKRlZYdG1XaFJHYmFkVldxSjBUV3hHWllKbVJXeG1WemdHZFdoa1dMSm1WS0pYWUdwMVZqaGxRR2xsVmF0VVlzWmxOV3BtUk9sRlZzSm5WdUoxZFNWVk5XWlZiNGgxVkdsVmVaaGxTcmRsUmtSRFZXUm1UaFpGY1hWbGVaaFhUR2wxZFUxR2VYUldNV1ZsV0dSMlFTWkVjdmQxYWFsV1dWbEVlVzVtU2hKMlJHTlhaRlJtYVhkMGQ0bDFWd2RWWXNwRldsVkVaUEZHTXdWRlZZNTBSU0pqU29OVmIxY0ZaSGhuTlpabFQwSW1WT3BrVXFwMFVOZEVhelpGV3dwa1VzNUVhWHRtV2hGV1J3UlhWclZ6U1daa1c0ZDFhV2hXWVZCWGNXaEZjaEoyUkt4a1dIaG5WU0ZqUzBaVmIwRm1VV0JYVU5abFZUTldNS1ZuVnU1MFFORmpUdlYyUnhnRlp3WUZXVjFXT3ZKbVZhZDBZR3AxVVh0V05GbDFNS0ZtVXRwRWFUdEdhWFJtUktWblZ5QTNUaHhtUllwRlJHZFZUSEoxY1daRlpETjFSV1JWWkZSV1lXWmtTWWxsYVNObllHcFZNalJrUVdSMWFhRm5WdVIyYU5kbFJZSmxhS1psVnNwVlJhWlVXNEptVkpwM1ZycFZhakpEZTFabGJPdGtZSFpFV05WRlpvTjFSM2hIVllSMlJXRmpVWmQxYVc5a1ZISjFWVXhHYlBKbVJLaG1VdFZ6VmxaVVI1WmxSa0ZtVldsa01VMVdNVGxWVjFNblZHdFdNU2RsVVlGMlI0WkZWR0IzUloxbVJEZGxSYUJUVnE1a1ZYWkVjeVoxTXdObFlHcEZVUGRGZGFOMk1DZEZWV2xFZVdCVE5hVjFhYWxHWndBWGRXdEdaTDEwUkdoVlRXUkdWa0pUT1hWVmJHZFVUc3htTlRSbFFUWkZNYVZsVjZKMVNpVlVNVWRGYlNWbFZzQjNWWlpGY3Ixa1Z2QmpXR3AxVldCaldZWlZSa2RuVnNSV2NhWmtWT2RWUjBnblZxSjFhaEZqVzBVVlZrNVVZRnBWUlp4R2JQWlZNS2hWWUdSbVdqTmpReWxWTWFGbVVzQlhVVDFHZU9ORk13VjFWVlIyYlNGRFpZSkZiU1JsVFlGRWVWNW1USEptVnNoa1RWWkZhV05qVTBaMU1DTm5Vc3BGV1RwbVRYZFZWdmhYV3NSMlNoeG1WYVpGYmtOVll3b0ZXV2gwWTBJbE1XRldWdGgzVVpWRmMwVlZiMHRXVEd4bVJYdG1Wb2RGU29SblZ4ZzJVaWRrU3pvMVI0ZEZaSUprUlZGalQwSVZNd2hHVnFwa1RSSmpVR1pGYmtkblVWRkRWVDFHY1RWMVZSaFhXWFZVTU5aa1YwSW1lR05sVjZaRmRXZDFaNEZXTUtoMlRYUkhXVGQwWjZaMVZzTmtVSDVrV1d4bVdwMUVTU1JuVnU1MFFYZGtWelZWYjBSMVlXOUdlVWRWT3ZabFZrcDFZRVpFVmhaRmN6VlZNUzlrWVdwa2RXMUdlWFpsYXJsbldHUkdOaVpsVk5aRmJrbFdWcnBVY1dCRFozMWtWYUIzVXRCblZXSmpVemwxYTVja1lXWkZNT1psVlhGbU1TWkZWV1IyVFNCRE00UmxWb2RGWldsVWVaWmxUaEptUmtsbFV0RnpVVnBIYnlabGJrWm5WdDVFV1d0bVdwVlZSd1JuVnJSM2JpWmxVWWRWYjRoVllyVlRjVmhGYnpaMWF4Z21VdEZqV1NCemI0bEZiUmhuVndFVFZVdG1XTzFrVnNGblZzeDJTTlpsV3pWMlJ4Z2xWdUZFZVZwbVFoMWtWV3AxVXFKMFZXTmpRMFYxYWtGbVZyRmplVnRtVVhaRldCZFhXV1JHTlNKalQyY0ZiYTVrWXdVVGRXNW1UM1pGYnNCWFZ0UlhWWGRrVXpabGJhOTJWR3AxTVdabFVhRldSYUZuVkhaMFRTMW1Tb0pXUmtGV1pWdEdlV3hHYVhKbVJrVlVUV1psVFRCalcwWmxSb2RrVUdSMlRUMUdjV1ZHYmFkVVdyaFROV0ZqVVlOV1JhNVVZR0JuUlpaRmFySkZiS2hVWUdaRldXSnpaNVpGYk9SallXUm1kVnBtU1RWMlJOaDNWWUJuU05ka1RvZFZiMEpWWUZCM1JaNUdackptUmFoM1lFSmtWVTFtVXlabFZvRldUWFowU2hkVU5YSkZNYVpWVkIxVFA)

[Conditional Jump - Same as above but loop until the data matches 'hello' or until 1000 iterations](https://gchq.github.io/CyberChef/#recipe=Label('top')Reverse('Character')From_Base64('A-Za-z0-9%2B/%3D',true,false)Conditional_Jump('hello',true,'top',1000)&input=UVJWTUNabFZhRldUR3BFV09WRlpvTkZNYWhGVlhaMGJOWmxXNGRsYUNaVllIaG1SWlJsUWhKVmJLcG5XSGgzVmxkVU95bFZNT1JqVXhBM1ZPVmxWcGRWYlNWblZ3UTJVU0JUTVlGRmJTQmxUVlZ6Vlo1R2FPWkZiYVZ6VVVaMFZXcG5WMFpWVm90VVRXcEVTUFJsU1hOV013ZGtWd1V6U1Nka1YySTJSNGRWWXpJRmRXNW1UTFpGYmtoMVlIRmpVanhHY0haMWFrOVdZeFFHU1ZwbVNWVkZNS1ZGVlZGelNpWmxTb3BsUmFGbVVWQm5jV3htVmhKbVJTMWtVclJXYVZCalcwWkZNV0ZtVVhaVVlWMUdlWFpWTXdkRlZYWjBhaXhtVzZWMWFraEZWeG8xUlgxV09YSjJWR1IwVnNaRldqRlRTNVZWVjFjVVlzUjJNV1JsUm9KbU1vZDFWV3AxVldaa1dYVlZiNFoxVkY5V2VWdEdadjFrUmFCalZ0QkhXVkJEY0ZwRld3TmxZR3BsY2FkVU5hWjFNQ1psV1dkR2VTSmpWNk5GYmE1MFV5ZzNjVzVtVmgxMFZTOTBWdFJYVlZka1VYbGxhUzlXVFdwRldScG1UVGRsYUdSWFZ1bEVlaEZqVzZOR1JPcGxVczlHZVpaRlpMRkdiV2gwWUdwMVVpSmpVeVpGV3NablZYNTBiVjFHZFZkbFJKbFhWdGx6Y1d4R1pZVmxhS0psVnhvbFZVcG1SMlpGYktoV1lGcDFWa0pUT0hwbFJrRldUV0JITk5kRWRUVmxNbmxuVnVKMVVUWkVaV0oxYVNwMlZHcDBWVzVHWlAxVU1XaDBZRVowVmh4bVN5VkZXQ3RtWUdwME1UMVdOWDUwYXZoblZIeDJhaEZqU0dKVmJ4TVZZeUkxVlg1bVVUSlZNT2gyVnJaVllUVjBiNFYxYWtOWFRXWmxlalprV29aVlJhRlhWeGcyYU5kbFIycGxSV0YyWXpJMFZaRkRhd0ltVmtoSFZ0aDNVWmRsVUhaRmJzOWtWd1VEY1h0bVdwTlZWMWdVVnI1MGNpWmxXS0ZXUmt0bVZ3VVRjVlpsUUwxMFZHTmpXeVV6VlhkMFo2WkZib05sVnNsbGVXdG1XTzFVVldSM1ZWUjJVU0JUTllOMlJ4UWxWR3BGZFZ0bVd2SkdiYWhWVnFwa1VVdG1XeFZsTW5GalZXcGxjU3BtU1dKMWFLbGtXR1JHTlNGRGNGSjFha2xXVnlFRmVXNW1TMzFrVmFsVlRYRmpWbHhHY1haVmIwdDJWR0pGV2laa1dPWmxWd05uVnhvVllOZGxSb1pWYjBkMVl3bzFSYVpGWkRaVlIxRTJZR3AxVVpkRmF6ZEZXb1puVlhKRldSdG1Vb1JtYUdaVVdyaFROV0ZEY0pKVmJ3ZDFWc0IzY1ZORGN6WkZiWmQzVFhSM1ZqQlRTNlZGYktCallXWmxlWHBtUk9WVk1LVm5WdWhtU1d4R2JQZFZiNFIxVlhKMVZacG1VckpGYndsVVlHUkdXV3BuUklsbGVDcGtZRkZEVWlkRWRhSjFNQ2RWV1ZWelVTZFZTM3BsUmFkVll3b0ZkVzVtVWhaVmJPaFZUVlIyYVhWVk4wVmxiYTkyVkdSMlZWcG1UWFpWTXdkMFZxSmtTaWRsVklwbFJhcDFWRkIzY1pGalcwSW1WWnBYVFhSM1ZUMUdhWlpsZWFGV1l4UTJja1ZFWnBWbVZhZFVXdVJHTWlaRmJJTkdSQ2xXVnpnR1NYdFdPSDEwYXhNVVlIVnpWa1YxYjRsRmJvdFdZeG9VVlV4bVdwUldNd2QxVnNSMlFOSmpUaDFVVmtCVlpHeDJWVVpsVERWR2JzZDBWcVowVldoRmFJbEZNb3RtVXRwMFVTeG1VVkoxTUJoblZYaFdZU2RsUmFwMVI0TkZadEpWV1dORGFTMUViS1IxVnJabGFoVjBiNGwxVjA5VVRXWjFNVlZsVXNaMU1TaFVXcmgzU1MxbVNRSlZieGMxWXVKMFJaWmxWWEoxVk5kblZxWkVhTmhrVXlkRldPRm1VdFpGVVYxR2VTZFZSYVJIVlc1VVlXWkZaWEZGYm9wVlZ6SUZTVVJsVUwxa1ZhUnpWVVowVlNaRmN6WkZia3RrVUhwVVZTeEdaT05WTXdWblZZcDBVaVpsVVZGRmJTaGxUc0IzUloxR2RQWkZiU0J6VXJwMVZpWmtXR2RWYm90bVlHcEVUaFprV1hSbVJKcFhWczUwUmh4MlkzSlZWYWRGVnpFVWVXNW1WdkpsTVNoVllIUkhXaFZFYzBWVmJHdGtZc1JXU2hkVU5ZWmxSYWRWVjZwVllOWmxXMkpWYnhZRlpFWmxjVXhHYTNKbVZLQlZWc1JtVGtGVFc2WkZiYU5WVHRKRlZYdG1XaFJHYmFkVldxSjBUV3hHWllKbVJXeG1WemdHZFdoa1dMSm1WS0pYWUdwMVZqaGxRR2xsVmF0VVlzWmxOV3BtUk9sRlZzSm5WdUoxZFNWVk5XWlZiNGgxVkdsVmVaaGxTcmRsUmtSRFZXUm1UaFpGY1hWbGVaaFhUR2wxZFUxR2VYUldNV1ZsV0dSMlFTWkVjdmQxYWFsV1dWbEVlVzVtU2hKMlJHTlhaRlJtYVhkMGQ0bDFWd2RWWXNwRldsVkVaUEZHTXdWRlZZNTBSU0pqU29OVmIxY0ZaSGhuTlpabFQwSW1WT3BrVXFwMFVOZEVhelpGV3dwa1VzNUVhWHRtV2hGV1J3UlhWclZ6U1daa1c0ZDFhV2hXWVZCWGNXaEZjaEoyUkt4a1dIaG5WU0ZqUzBaVmIwRm1VV0JYVU5abFZUTldNS1ZuVnU1MFFORmpUdlYyUnhnRlp3WUZXVjFXT3ZKbVZhZDBZR3AxVVh0V05GbDFNS0ZtVXRwRWFUdEdhWFJtUktWblZ5QTNUaHhtUllwRlJHZFZUSEoxY1daRlpETjFSV1JWWkZSV1lXWmtTWWxsYVNObllHcFZNalJrUVdSMWFhRm5WdVIyYU5kbFJZSmxhS1psVnNwVlJhWlVXNEptVkpwM1ZycFZhakpEZTFabGJPdGtZSFpFV05WRlpvTjFSM2hIVllSMlJXRmpVWmQxYVc5a1ZISjFWVXhHYlBKbVJLaG1VdFZ6VmxaVVI1WmxSa0ZtVldsa01VMVdNVGxWVjFNblZHdFdNU2RsVVlGMlI0WkZWR0IzUloxbVJEZGxSYUJUVnE1a1ZYWkVjeVoxTXdObFlHcEZVUGRGZGFOMk1DZEZWV2xFZVdCVE5hVjFhYWxHWndBWGRXdEdaTDEwUkdoVlRXUkdWa0pUT1hWVmJHZFVUc3htTlRSbFFUWkZNYVZsVjZKMVNpVlVNVWRGYlNWbFZzQjNWWlpGY3Ixa1Z2QmpXR3AxVldCaldZWlZSa2RuVnNSV2NhWmtWT2RWUjBnblZxSjFhaEZqVzBVVlZrNVVZRnBWUlp4R2JQWlZNS2hWWUdSbVdqTmpReWxWTWFGbVVzQlhVVDFHZU9ORk13VjFWVlIyYlNGRFpZSkZiU1JsVFlGRWVWNW1USEptVnNoa1RWWkZhV05qVTBaMU1DTm5Vc3BGV1RwbVRYZFZWdmhYV3NSMlNoeG1WYVpGYmtOVll3b0ZXV2gwWTBJbE1XRldWdGgzVVpWRmMwVlZiMHRXVEd4bVJYdG1Wb2RGU29SblZ4ZzJVaWRrU3pvMVI0ZEZaSUprUlZGalQwSVZNd2hHVnFwa1RSSmpVR1pGYmtkblVWRkRWVDFHY1RWMVZSaFhXWFZVTU5aa1YwSW1lR05sVjZaRmRXZDFaNEZXTUtoMlRYUkhXVGQwWjZaMVZzTmtVSDVrV1d4bVdwMUVTU1JuVnU1MFFYZGtWelZWYjBSMVlXOUdlVWRWT3ZabFZrcDFZRVpFVmhaRmN6VlZNUzlrWVdwa2RXMUdlWFpsYXJsbldHUkdOaVpsVk5aRmJrbFdWcnBVY1dCRFozMWtWYUIzVXRCblZXSmpVemwxYTVja1lXWkZNT1psVlhGbU1TWkZWV1IyVFNCRE00UmxWb2RGWldsVWVaWmxUaEptUmtsbFV0RnpVVnBIYnlabGJrWm5WdDVFV1d0bVdwVlZSd1JuVnJSM2JpWmxVWWRWYjRoVllyVlRjVmhGYnpaMWF4Z21VdEZqV1NCemI0bEZiUmhuVndFVFZVdG1XTzFrVnNGblZzeDJTTlpsV3pWMlJ4Z2xWdUZFZVZwbVFoMWtWV3AxVXFKMFZXTmpRMFYxYWtGbVZyRmplVnRtVVhaRldCZFhXV1JHTlNKalQyY0ZiYTVrWXdVVGRXNW1UM1pGYnNCWFZ0UlhWWGRrVXpabGJhOTJWR3AxTVdabFVhRldSYUZuVkhaMFRTMW1Tb0pXUmtGV1pWdEdlV3hHYVhKbVJrVlVUV1psVFRCalcwWmxSb2RrVUdSMlRUMUdjV1ZHYmFkVVdyaFROV0ZqVVlOV1JhNVVZR0JuUlpaRmFySkZiS2hVWUdaRldXSnpaNVpGYk9SallXUm1kVnBtU1RWMlJOaDNWWUJuU05ka1RvZFZiMEpWWUZCM1JaNUdackptUmFoM1lFSmtWVTFtVXlabFZvRldUWFowU2hkVU5YSkZNYVpWVkIxVFA)

The closest thing I can see is the alu operation, but this seems to be for mathematical operations, or maybe I am missing something

**Comment by huettenhain** [comment]
You are in luck! I just added the `loop` unit in 0.7.1, which can already do the first thing:
```
$ emit data | loop 21 rev:b64
hello
```
It does not have an option yet to halt iteration based on a condition, but that was something I had already planned to add as a feature. I'll update this ticket once it's in.

**Comment by huettenhain** [comment]
With the changes from 91f6fd0, you can now also do the following things:
```
$ emit data | loop 1k rev:b64 -v --until hello
(17:26:05) comment in loop: step 0021: stopping, until-condition satisfied
hello
$ emit data | loop 1k rev:b64 -v
(17:26:11) comment in loop: step 0021: stopping after error; Invalid base64-encoded string: number of data characters 
(5) cannot be 1 more than a multiple of 4
hello
```
The log messages will not usually appear, I added the `-v` switch to illustrate what is happening: You can manually specify a regex-based abort condition, which in this case mimics the one you used in CyberChef. It will, however, also just quietly abort as soon as the suffix evaluation fails and return the previous result. I am still pondering whether this should be the default behaviour or locked behind the `--lenient` switch.

**Comment by huettenhain** [comment]
I decided that locking this behind leniency is the better choice; see bb585509.

**Comment by huettenhain** [comment]
This is [currently being released](https://github.com/binref/refinery/actions/runs/10761879074) in 0.7.2.

**Comment by Ben4FH** [comment]
Thank you so much for the quick implementation of this. Just tested and it works great!
