### ISSUE TITLE
IFPS: Imported but non-Exported function does not get a valid DeclSpec

### ISSUE THREAD

**Issue by gdesmar** [binref/refinery#58]
### Description
When reading this specific IFPS file with the IFPS unit, the following error happens:
> exception of type AttributeError; 'NoneType' object has no attribute 'represent'

When trying to read it from a python prompt, we can get the full stack trace:
```python
  File ".../refinery/lib/structures.py", line 696, in wrapped__init__
    original__init__(self, reader, *args, **kwargs)
  File ".../refinery/units/formats/ifps.py", line 592, in __init__
    self._load_functions()
  File ".../refinery/units/formats/ifps.py", line 718, in _load_functions
    instruction.operands[0] = t.reference()
                              ^^^^^^^^^^^^^
  File ".../refinery/units/formats/ifps.py", line 459, in reference
    return self.decl.represent(self.name, ref=True)
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'represent'
```

From my limited understanding, seven functions (with the first being GETARRAYLENGTH) are imported, but not exported, so the value of `decl` stays with the [default](https://github.com/binref/refinery/blob/master/refinery/units/formats/ifps.py#L696) `None`. From looking at other IFPS files, those functions are usually exported too, to result in a line similar to `external function GETARRAYLENGTH();`.

### To Reproduce
The original [InnoSetup file](https://www.virustotal.com/gui/file/91df2a8013c85cd959b92bffc88d5f1ff70546cc25a9ad1d948b0cdff17677ec) gives out an IFPS file named [CompiledCode.bin](https://github.com/user-attachments/files/16911091/CompiledCode.bin.zip) (attached, with password binref). This is the file causing the issue.

### Environment
- Operating System: Debian bullseye
- Python Version: Python 3.11.7
- Refinery Version: 0.7.0

### Additional Context
I ran [IFPSTools.NET](https://github.com/Wack0/IFPSTools.NET) on the CompiledCode.bin and got this resulting [CompiledCode.txt.zip](https://github.com/user-attachments/files/16911108/CompiledCode.txt.zip) (attached, with password binref), in case it could help in any way.

Another function that is causing problem in this file is EXPANDCONSTANT. It gets decompiled as the following with IFPSTools:
```.function external  void EXPANDCONSTANT```
Finding the same function in another IFPS file that does not cause an issue in BinaryRefinery gives:
```.function(import) external internal returnsval EXPANDCONSTANT(__in __unknown)```
So it may point out to a corruption in the IFPS file, as IFPSTools does not look to handle it that much more cleanly either.

**Comment by huettenhain** [comment]
Thank you for the bug report! The solution I propose (because I see no other way to handle this) is to accept that we don't have a type signature for these external symbols. The fix implemented in 3e78164 will output the following header:
```
external symbol GETARRAYLENGTH;
external symbol POS;
external symbol STRINGCHANGE;
external symbol EXPANDCONSTANT;
external symbol LOADSTRINGSFROMFILE;
external symbol GETSHORTNAME;
external symbol SAVESTRINGSTOFILE;
```
and then a call in the code will look like this:
```
  0x02F  SetPtr      LocalVar4, Argument1
  0x03A  PushVar     LocalVar3
  0x040  Call        GETARRAYLENGTH
  0x045  Pop
  0x046  Pop
```
I will compile a bugfix release soon.

**Comment by huettenhain** [comment]
PS: You can run `ifps -vv` to get a full call trace - that way you don't have to spin up an interpreter next time you find an odd IFPS =).

**Comment by huettenhain** [comment]
This [is currently being released](https://github.com/binref/refinery/actions/runs/10761879074) in 0.7.2.

**Comment by gdesmar** [comment]
Perfect! Thank you very much!

**Comment by huettenhain** [comment]
Hey @Wack0, apologies! I should have forwarded this to you. Conversely, thanks for pinging back here. If I have any future IFPS stuff that comes up and we see odd IFPSTools behaviour, I hereby promise that we will let you know. Cheers!
