### ISSUE TITLE
Dependency mismatch issues (angr x Unicorn) causing different behavior between installation selections

### ISSUE THREAD

**Issue by alphillips-lab** [binref/refinery#66]
### Description
Dependency management issue across units

### To Reproduce
Install a minimal build of refinery, use `vstack`, follow the steps to install the latest version of unicorn using `pip`. There is an API issue with the way line 330 in `vstack` (`UC_HOOK_MEM_READ_AFTER` hook, confirmed in release `0.7.4`) is initialized in the latest version of unicorn that is installed with pip (`2.1.1`)

angr is used in the `vmemref` unit, which has an upstream dependency requirement for unicorn version `2.0.1.post1`, https://github.com/angr/angr/blob/master/pyproject.toml

This means that installing a full build of refinery ends up with the unicorn version `2.0.1.post1` since that is what angr depends on. The `vstack` unit works on this version of unicorn, implying you maybe develop it in a virtual environment with angr installed.

In contrast, installing a minimal build of refinery with limited dependencies, then trying to use `vstack` will tell you to install the latest version of unicorn, which won't work for that unit. You wouldn't know until installing `angr` into the same virtual environment, when it reinstalls unicorn to its required version.

### Environment
- Operating System: All
- Python Version: All
- Refinery Version: Latest

### Additional Context
Open discussion on how this should be resolved, but I think the most sensible option is to continue with the old version of unicorn unless otherwise necessary, since angr depends on it, and develop `vstack` and other memory manipulating units with that in mind. I would also propose updating the requirements for `vstack` to push this version for minimal builds as well:

Line 83 in `vstack` https://github.com/binref/refinery/blob/master/refinery/units/formats/exe/vstack.py#L83
```
@Unit.Requires('unicorn', 'default', 'extended')
<---
@Unit.Requires('unicorn==2.0.1.post1', 'default', 'extended')
```

**Comment by huettenhain** [comment]
Pinning the version is definitely a good stop-gap solution. Ultimately, I think I'd like to get rid of angr in `vmemref` and replace it with something like [smda](https://github.com/danielplohmann/smda), though.

**Comment by huettenhain** [comment]
I am [releasing refinery-0.7.5](https://github.com/binref/refinery/actions/runs/11424608554) which includes the fix for this issue. I'll close this as resolved since I don't want the issue to go stale; I am not sure when I will find the time to work on `vmemref`.

**Comment by alphillips-lab** [comment]
Ah nice! I’m unfamiliar with smda but i’ll have to check it out. I am also not a huge fan of anger’s CFG recovery capabilities
